import type { Metadata } from 'next'
import './globals.css'
import ThemeProvider from '~/components/ThemeProvider'
import Body from '~/components/Body'

// import { Inter } from 'next/font/google'
// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <ThemeProvider>
        <Body>{children}</Body>
      </ThemeProvider>
    </html>
  )
}
